<a href="https://colab.research.google.com/github/nabigwaku/python/blob/master/Advanced_Data_Selection_%26_Filtering_using_loc_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

The `loc` function in Pandas is a tool for accessing specific rows and columns in a DataFrame using labels or boolean arrays.

### Syntax
```python
pandas.DataFrame.loc[row_labels, column_labels]

# Objectives

1. Explore the usage of loc
2. Understand alternatives to loc

The loc function is used to access a group of rows and columns by labels or a boolean array.

**Syntax:**

*`pandas.dataframe.loc[row_labels,column_labels]`*

**Objectives:**
1. Usage of loc
2. Alternatives of Loc

## 1. Usage of Loc:

One can select single cell, multiple cells of row and columns based on given conditions

### a). Selecting rows and columns by label:

Syntax:

`df.loc['label1']`

In [34]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Moses','Eddie','Walligo','Bahai'],
    'Age': [23,45,12,45,32,56,78,23],
    'Marks': [78,91,9,12,56,78,90,100],
    'Gender': ['Female','Male','Male','Male','Male','Male','Male','Male'],
    'location': ['kampala','Komamboga','Makerere', 'Kampala', 'Kikoni','Kyebando', 'Makerere', 'Matuga'],
    'Country': ['Uganda','Uganda','Uganda','Uganda','Uganda','Uganda','Uganda','Uganda'],
    'City': ['Kampala','Kampala','Kampala','Kampala','Kampala','Kampala','Kampala','Kampala'],
    'Region': ['Eastern','Central','Central','Eastern','Cental','Eastern','Western','Eastern'],
    'tuiton': [234,123,456,32,67,897,334,567],
    'course_work':[23,45,65,100,23,56,78,90]

}

df = pd.DataFrame(data)
df

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23
1,Bob,45,91,Male,Komamboga,Uganda,Kampala,Central,123,45
2,Charlie,12,9,Male,Makerere,Uganda,Kampala,Central,456,65
3,David,45,12,Male,Kampala,Uganda,Kampala,Eastern,32,100
4,Moses,32,56,Male,Kikoni,Uganda,Kampala,Cental,67,23
5,Eddie,56,78,Male,Kyebando,Uganda,Kampala,Eastern,897,56
6,Walligo,78,90,Male,Makerere,Uganda,Kampala,Western,334,78
7,Bahai,23,100,Male,Matuga,Uganda,Kampala,Eastern,567,90

In [6]:
## selecting row 1 values along with the column heads
df.loc[0]

Name          Alice
Age              23
Marks            78
Gender       Female
location    kampala
Country      Uganda
City        Kampala
Region      Eastern
Name: 0, dtype: object

In [8]:
# selecting 1st 2 rows
df.loc[:1]

    Name  Age  Marks  Gender   location Country     City   Region
0  Alice   23     78  Female    kampala  Uganda  Kampala  Eastern
1    Bob   45     91    Male  Komamboga  Uganda  Kampala  Central

In [16]:
## select rows and columns of interest
df1 = df.loc[:1,'Name']

df2 = df.loc[:1,['Name','Marks']]

df3 = df.loc[:1,['Name','Marks','Age']] # all rows from 0 to 1 with selected columns

df4 = df.loc[:,['Name','Marks','Age','Gender']] # all rows with selected columns

df5 = df.loc[[0,3,6,7],['Name','Marks','Age','Gender']] # selected rows with selected columns

print(df1,df2,df3,df4,df5, sep='\n\n')

0    Alice
1      Bob
Name: Name, dtype: object

    Name  Marks
0  Alice     78
1    Bob     91

    Name  Marks  Age
0  Alice     78   23
1    Bob     91   45

      Name  Marks  Age  Gender
0    Alice     78   23  Female
1      Bob     91   45    Male
2  Charlie      9   12    Male
3    David     12   45    Male
4    Moses     56   32    Male
5    Eddie     78   56    Male
6  Walligo     90   78    Male
7    Bahai    100   23    Male

      Name  Marks  Age  Gender
0    Alice     78   23  Female
3    David     12   45    Male
6  Walligo     90   78    Male
7    Bahai    100   23    Male

### b). Boolean Indexing (Filtering):

Suppose one wants entries or records with certain conditions

Syntax:

`df.loc[df['column_name'] > some_value]`

In [23]:
sel_df_1 = df.loc[df['Age'] <= 20] ## selecting values where age is less than or equal to 20

sel_df_2 = df.loc[df['Marks'] >= 70] ## selecting values where marks is greater or equal to 70

print(sel_df_1,sel_df_2, sep='\n\n')

      Name  Age  Marks Gender  location Country     City   Region
2  Charlie   12      9   Male  Makerere  Uganda  Kampala  Central

      Name  Age  Marks  Gender   location Country     City   Region
0    Alice   23     78  Female    kampala  Uganda  Kampala  Eastern
1      Bob   45     91    Male  Komamboga  Uganda  Kampala  Central
5    Eddie   56     78    Male   Kyebando  Uganda  Kampala  Eastern
6  Walligo   78     90    Male   Makerere  Uganda  Kampala  Western
7    Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern

**One can also use:**
* & --> for Multiple Conditions,
* | --> for OR Conditions
* Use both AND (&) and OR (|) at once too.
* Based on Calculated Conditions

As seen in scenarios below::

In [30]:
sel_df_3 = df.loc[ (df['Age'] < 50) & (df['Marks'] >= 70)] # selecting where age is less than 50 and marks greater or equal to 70

sel_df_4 = df.loc[ (df['Age'] < 50) | (df['Marks'] >= 70)] # selecting where age is less than 50 or marks greater or equal to 70

sel_df_5 = df.loc[ (df['Age'] < 50) & (df['Marks'] >= 70) & (df['Gender'] == 'Male')] # selecting where age is less than 50 and marks greater or equal to 70 and gender is male

print(sel_df_3,sel_df_4,sel_df_5, sep='\n\n')

    Name  Age  Marks  Gender   location Country     City   Region
0  Alice   23     78  Female    kampala  Uganda  Kampala  Eastern
1    Bob   45     91    Male  Komamboga  Uganda  Kampala  Central
7  Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern

      Name  Age  Marks  Gender   location Country     City   Region
0    Alice   23     78  Female    kampala  Uganda  Kampala  Eastern
1      Bob   45     91    Male  Komamboga  Uganda  Kampala  Central
2  Charlie   12      9    Male   Makerere  Uganda  Kampala  Central
3    David   45     12    Male    Kampala  Uganda  Kampala  Eastern
4    Moses   32     56    Male     Kikoni  Uganda  Kampala   Cental
5    Eddie   56     78    Male   Kyebando  Uganda  Kampala  Eastern
6  Walligo   78     90    Male   Makerere  Uganda  Kampala  Western
7    Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern

    Name  Age  Marks Gender   location Country     City   Region
1    Bob   45     91   Male  Komamboga  Uganda  Kampala  Central
7  Bahai   23    100   Male     Matuga  Uganda  Kampala  Eastern

#### Use both AND (&) and OR (|) at once too.

In [31]:
sel_df_6 = df.loc[ (df['Age'] < 50) & (df['Marks'] >= 70) | (df['Gender'] == 'Male')] # selecting where age is less than 50 and marks greater or equal to 70 or gender is male

print(sel_df_6, sep='\n\n')

      Name  Age  Marks  Gender   location Country     City   Region
0    Alice   23     78  Female    kampala  Uganda  Kampala  Eastern
1      Bob   45     91    Male  Komamboga  Uganda  Kampala  Central
2  Charlie   12      9    Male   Makerere  Uganda  Kampala  Central
3    David   45     12    Male    Kampala  Uganda  Kampala  Eastern
4    Moses   32     56    Male     Kikoni  Uganda  Kampala   Cental
5    Eddie   56     78    Male   Kyebando  Uganda  Kampala  Eastern
6  Walligo   78     90    Male   Makerere  Uganda  Kampala  Western
7    Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern

#### Based on Calculated Conditions

1. Pick those who are below 60% when we add up their marks and course_work

In [37]:
con_df1 = df.loc[(df['Marks']+df['course_work'])/2 < 60]
con_df1

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23
2,Charlie,12,9,Male,Makerere,Uganda,Kampala,Central,456,65
3,David,45,12,Male,Kampala,Uganda,Kampala,Eastern,32,100
4,Moses,32,56,Male,Kikoni,Uganda,Kampala,Cental,67,23

**Exercise:**
1. Create column called overall_mark that sum of marks and course_work divided by 2, then add a final_review column for::
  * those with overall mark less than 40 as fail
  * overall mark between 41 and 60 as average
  * and overall mark great than 60 as passed

2. Select all those who names start with A OR B OR C alphabet letters
3. Select all with locations in Kampala, Kikoni

##### Steps 1: Creating empty columns for overall_mark and final_review

In [40]:
# Steps 1: Creating empty columns for overall_mark and final_review
## Create overall_mark column
df['overall_mark'] = None
## Create final_review column
df['final_review'] = None

df.head(2)

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work,overall_mark,final_review
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23,None,None
1,Bob,45,91,Male,Komamboga,Uganda,Kampala,Central,123,45,None,None

##### Steps 2: Calculate overall_mark values

In [41]:
df['overall_mark'] = (df['Marks']+df['course_work'])/2
df.head(2)

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work,overall_mark,final_review
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23,50.5,None
1,Bob,45,91,Male,Komamboga,Uganda,Kampala,Central,123,45,68.0,None

##### Steps 3: Add final_review values

In [44]:
# when overall_mark below 40 then fail
df.loc[df['overall_mark'] < 40, 'final_review'] = 'Fail'

# when overall_mark between 41 and 60 then average
df.loc[df['overall_mark'].between(41,60), 'final_review'] = 'Average'

# when overall_mark greater than 6 then passed
df.loc[df['overall_mark'] > 60, 'final_review'] = 'Passed'

df.head(10)

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work,overall_mark,final_review
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23,50.5,Average
1,Bob,45,91,Male,Komamboga,Uganda,Kampala,Central,123,45,68.0,Passed
2,Charlie,12,9,Male,Makerere,Uganda,Kampala,Central,456,65,37.0,Fail
3,David,45,12,Male,Kampala,Uganda,Kampala,Eastern,32,100,56.0,Average
4,Moses,32,56,Male,Kikoni,Uganda,Kampala,Cental,67,23,39.5,Fail
5,Eddie,56,78,Male,Kyebando,Uganda,Kampala,Eastern,897,56,67.0,Passed
6,Walligo,78,90,Male,Makerere,Uganda,Kampala,Western,334,78,84.0,Passed
7,Bahai,23,100,Male,Matuga,Uganda,Kampala,Eastern,567,90,95.0,Passed

##### Step 5: Selecting those whose names start with letter A or B or C

In [46]:
cond_sel_1 = df.loc[(df['Name'].str[0] == 'A') | (df['Name'].str[0] == 'B') | (df['Name'].str[0] == 'C')]

## or

cond_sel_2 = df.loc[df['Name'].str.startswith(('A','B','C'))]

print(cond_sel_1,cond_sel_2, sep='\n\n')

      Name  Age  Marks  Gender   location Country     City   Region  tuiton  \
0    Alice   23     78  Female    kampala  Uganda  Kampala  Eastern     234
1      Bob   45     91    Male  Komamboga  Uganda  Kampala  Central     123
2  Charlie   12      9    Male   Makerere  Uganda  Kampala  Central     456
7    Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern     567

   course_work  overall_mark final_review
0           23          50.5      Average
1           45          68.0       Passed
2           65          37.0         Fail
7           90          95.0       Passed

      Name  Age  Marks  Gender   location Country     City   Region  tuiton  \
0    Alice   23     78  Female    kampala  Uganda  Kampala  Eastern     234
1      Bob   45     91    Male  Komamboga  Uganda  Kampala  Central     123
2  Charlie   12      9    Male   Makerere  Uganda  Kampala  Central     456
7    Bahai   23    100    Male     Matuga  Uganda  Kampala  Eastern     567

   course_work  overall_mark final_review
0           23          50.5      Average
1           45          68.0       Passed
2           65          37.0         Fail
7           90          95.0       Passed

##### Step 6. Selecting those located in kampala, kikoni

In [51]:
# lower - converting the location values to lower case, and strip() removes any trailing zeros
con_df2 = df.loc[df['location'].str.lower().str.strip().isin(['kampala', 'kikoni'])]
con_df2

,Name,Age,Marks,Gender,location,Country,City,Region,tuiton,course_work,overall_mark,final_review
0,Alice,23,78,Female,kampala,Uganda,Kampala,Eastern,234,23,50.5,Average
3,David,45,12,Male,Kampala,Uganda,Kampala,Eastern,32,100,56.0,Average
4,Moses,32,56,Male,Kikoni,Uganda,Kampala,Cental,67,23,39.5,Fail

##### Extra:: Summary of Common Patterns

```
SQL LIKE Pattern -->>	   Pandas .str.contains() Equivalent
* %value%	  --- df['col'].str.contains('value')
* value%  --- df['col'].str.contains('^value')
* %value	--- df['col'].str.contains('value$')
* _value	--- df['col'].str.contains('^.value')
* %val%ue%	--  df['col'].str.contains('val.*ue')

```

## 2. Alternatives of Loc

1. **[iloc](https://www.geeksforgeeks.org/python-extracting-rows-using-pandas-iloc/)**
Similar to loc but used when access the rows or columns based on their interger location index.

  Syntax:  ```
    df.iloc[0]          # First row
    df.iloc[1:3]        # Second and third rows
    df.iloc[:, [0, 2]]  # All rows, first and third columns
```
2. **[at](https://www.geeksforgeeks.org/python-pandas-dataframe-at/)**  Syntax::  ` df.at[position, label] `

3. **[Query Method](https://www.geeksforgeeks.org/pandas-query-method/)**   Syntax::  `  df.query('Age > 25')`